version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - ./:/home/sakairi
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]